### ISSUE TITLE
How was the file examples/5c2h_11.09 generated?

### ISSUE THREAD

**Issue by yipy0005** [wyji001/Point-Cloud#1]
Hi, I'm interested in using PointCloud to predict binding affinities for a protein of interest and a list of ligands, but I don't understand how was the file examples/5c2h_11.09 generated. Can you let me know the steps?

Thank you!

**Comment by Xinxinatg** [comment]
@yipy0005 Hi have you figured out the way to preprocess the pdb file? It seems like the author only provide the executable files ./POINTNET, ./POINTNET-2048 and ./POINTNET-atomchannel to process the pdb file but didn't give the details in regards to how to eleminate solvents, metals, and ions as decribed in the manuscript.
![image](https://user-images.githubusercontent.com/72983482/157578524-8b9de8d6-8580-44a5-a253-48fe9e1ad95a.png)

**Comment by wyji001** [comment]
Many software or libraries can achieve the function of removing solvents, metals, and ions, and using different software will not have any effect on the results. You can even write a simple script to remove manually

**Comment by Xinxinatg** [comment]
@wyji001 Thanks for your propt reply and again for your wonderful work! I am now using Protein Preparation Wizard in the Schrodinger suite to remove solvents, metals, and ions

**Comment by yipy0005** [comment]
@Xinxinatg I'm using Schrodinger's Protein Prep Wiz too! :D
